--> This is a code for recommendation on the basis of description

In [3]:
import pandas as pd
import numpy as np

In [4]:
data_ = pd.read_csv('games.csv')

data_

,BGGId,Name,Description,YearPublished,GameWeight,AvgRating,BayesAvgRating,StdDev,MinPlayers,MaxPlayers,...,Rank:partygames,Rank:childrensgames,Cat:Thematic,Cat:Strategy,Cat:War,Cat:Family,Cat:CGS,Cat:Abstract,Cat:Party,Cat:Childrens
0,1,Die Macher,die macher game seven sequential political rac...,1986,4.3206,7.61428,7.10363,1.579790,3,5,...,21926,21926,0,1,0,0,0,0,0,0
1,2,Dragonmaster,dragonmaster tricktaking card game base old ga...,1981,1.9630,6.64537,5.78447,1.454400,3,4,...,21926,21926,0,1,0,0,0,0,0,0
2,3,Samurai,samurai set medieval japan player compete gain...,1998,2.4859,7.45601,7.23994,1.182270,2,4,...,21926,21926,0,1,0,0,0,0,0,0
3,4,Tal der Könige,triangular box luxurious large block tal der k...,1992,2.6667,6.60006,5.67954,1.231290,2,4,...,21926,21926,0,0,0,0,0,0,0,0
4,5,Acquire,acquire player strategically invest business t...,1964,2.5031,7.33861,7.14189,1.335830,2,6,...,21926,21926,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21920,347146,Salvage,oil tanker fire rescue team send deal damage...,2021,0.0000,7.45000,5.52462,1.554930,3,4,...,21926,21926,0,0,0,0,0,0,0,0
21921,347521,Blitzkrieg!: World War Two in 20 Minutes,new square edition include nippon expansion up...,2019,1.6667,7.92276,5.56323,0.894204,1,2,...,21926,21926,0,0,0,0,0,0,0,0
21922,348955,Rock Paper Scissors: Deluxe Edition,million year people force play timehonored gam...,2021,4.5625,6.96970,5.53964,4.052570,1,3,...,21926,21926,0,0,0,0,0,0,0,0
21923,349131,Splitter,splitter group number score point mdash s s md...,2021,1.0000,6.48235,5.52631,1.160070,1,12,...,21926,21926,0,0,0,0,0,0,0,0
21924,349161,Captains' War,gather resource build crew fight rival claim p...,0,2.5000,9.91429,5.50806,0.368117,1,6,...,21926,21926,0,0,0,0,0,0,0,0

In [5]:
data_.columns

Index(['BGGId', 'Name', 'Description', 'YearPublished', 'GameWeight',
       'AvgRating', 'BayesAvgRating', 'StdDev', 'MinPlayers', 'MaxPlayers',
       'ComAgeRec', 'LanguageEase', 'BestPlayers', 'GoodPlayers', 'NumOwned',
       'NumWant', 'NumWish', 'NumWeightVotes', 'MfgPlaytime', 'ComMinPlaytime',
       'ComMaxPlaytime', 'MfgAgeRec', 'NumUserRatings', 'NumComments',
       'NumAlternates', 'NumExpansions', 'NumImplementations',
       'IsReimplementation', 'Family', 'Kickstarted', 'ImagePath',
       'Rank:boardgame', 'Rank:strategygames', 'Rank:abstracts',
       'Rank:familygames', 'Rank:thematic', 'Rank:cgs', 'Rank:wargames',
       'Rank:partygames', 'Rank:childrensgames', 'Cat:Thematic',
       'Cat:Strategy', 'Cat:War', 'Cat:Family', 'Cat:CGS', 'Cat:Abstract',
       'Cat:Party', 'Cat:Childrens'],
      dtype='object')

In [6]:
data_['Cat:Family'].value_counts()

Cat:Family
0    19609
1     2316
Name: count, dtype: int64

In [7]:
data_['Description']

0        die macher game seven sequential political rac...
1        dragonmaster tricktaking card game base old ga...
2        samurai set medieval japan player compete gain...
3        triangular box luxurious large block tal der k...
4        acquire player strategically invest business t...
                               ...
21920    oil tanker fire rescue team send deal   damage...
21921    new square edition include nippon expansion up...
21922    million year people force play timehonored gam...
21923    splitter group number score point mdash s s md...
21924    gather resource build crew fight rival claim p...
Name: Description, Length: 21925, dtype: object

In [8]:
data = data_[['Name', 'Description']]

data

,Name,Description
0,Die Macher,die macher game seven sequential political rac...
1,Dragonmaster,dragonmaster tricktaking card game base old ga...
2,Samurai,samurai set medieval japan player compete gain...
3,Tal der Könige,triangular box luxurious large block tal der k...
4,Acquire,acquire player strategically invest business t...
...,...,...
21920,Salvage,oil tanker fire rescue team send deal damage...
21921,Blitzkrieg!: World War Two in 20 Minutes,new square edition include nippon expansion up...
21922,Rock Paper Scissors: Deluxe Edition,million year people force play timehonored gam...
21923,Splitter,splitter group number score point mdash s s md...
21924,Captains' War,gather resource build crew fight rival claim p...

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import string

from nltk.corpus import stopwords
import nltk

In [10]:
# Check for rows where 'Description' column contains floats or non-string values
float_rows = data[~data['Description'].apply(lambda x: isinstance(x, str))]

# Display rows where 'Description' is not a string (e.g., floats)
print(float_rows)

                              Name Description
14243  Timeline: Sports et Loisirs         NaN

In [11]:
data = data.dropna()

In [12]:
data['Description'].values

array(['die macher game seven sequential political race different region germany player charge national political party manage limited resource help party victory win party victory point regional election different way score victory point regional election supply eighty victory point depend size region party second party win regional election medium influence region party receive mediacontrol victory point party national party membership grow game progress supply fair number victory point lastly party score victory point party platform match national opinion end gamethe   edition feature party old west germany support   player   edition support player reunite germany update feature rule     edition support player add short fiveround variant additional rule update original designer',
       'dragonmaster tricktaking card game base old game call coup dtat player give supply plastic gem represent point player dealer different hand slightly different goal hand card deal dealer decide hand good suit current card player penalize point form crystal take certain trick card instance quotfirstquot quotlastquot call player penalize take trick player chance dealer hand player steal opportunity take trick certain hand end big pile gem win gamejewel content clear   extra green   extra red   extra blue   extra',
       'samurai set medieval japan player compete gain favor faction samurai peasant priest represent helmet rice paddy buddha figure scatter board feature island japan competition wage use hexagonal tile help curry favor faction mdash player lightningquick strike horseback ronin ship approach conquest methodically figure helmet rice paddy buddha surround award player gain favor corresponding groupgameplay continue symbol type remove board figure remove play tie influenceat end game player compare capture symbol type compete majority type tie uncommon break base number quotnonmajorityquot symbol player collectedthe game call knizia tilelaye trilogy',
       ...,
       'million year people force play timehonored game rock paper scissor hand cheapen experience insult distinguished heritageuntil nowwe proud finally decorate game deluxe edition deservesthe game feature bull raw amethyst geode bull european embroidery scissor bull gold metallic performance paperinclude bull art beth sobel wingspan viticulture bull deep mythological lore chip theory game bull insert game trayz bull solo mode design david turczi',
       'splitter group number score point mdash s s mdash place number time thing wo nt work outeach player score sheet   space different pattern space include box pattern dash line middle split mirror halveson turn roll sixside dice player write result eg     space pattern number mirrored space place   leftmost space row place   rightmost space rowafter   dice roll everyone pattern fill   mdash s orthogonally adjacent mdash score   point set s orthogonally adjacent s score   point set s orthogonally adjacent s   worth   point starred space present half pattern score group contain starred space point double pattern set space heart fill heart number score   pointswhoever high score win',
       'gather resource build crew fight rival claim place rightful captain high seasa great rollandwrite adventure     playerson player turn roll dice draft single dice unique player pick   action detail remain dice'],
      dtype=object)

In [13]:
def preprocess_text(text):

    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    stop_words = set(stopwords.words('english'))
    text = ' '.join([word for word in text.split() if word not in stop_words])

    return text

In [14]:
data['ProcessedDescription'] = data['Description'].apply(preprocess_text)

C:\Users\Malhar.Pandya\AppData\Local\Temp\ipykernel_3832\350702872.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['ProcessedDescription'] = data['Description'].apply(preprocess_text)

In [15]:
data

,Name,Description,ProcessedDescription
0,Die Macher,die macher game seven sequential political rac...,die macher game seven sequential political rac...
1,Dragonmaster,dragonmaster tricktaking card game base old ga...,dragonmaster tricktaking card game base old ga...
2,Samurai,samurai set medieval japan player compete gain...,samurai set medieval japan player compete gain...
3,Tal der Könige,triangular box luxurious large block tal der k...,triangular box luxurious large block tal der k...
4,Acquire,acquire player strategically invest business t...,acquire player strategically invest business t...
...,...,...,...
21920,Salvage,oil tanker fire rescue team send deal damage...,oil tanker fire rescue team send deal damage f...
21921,Blitzkrieg!: World War Two in 20 Minutes,new square edition include nippon expansion up...,new square edition include nippon expansion up...
21922,Rock Paper Scissors: Deluxe Edition,million year people force play timehonored gam...,million year people force play timehonored gam...
21923,Splitter,splitter group number score point mdash s s md...,splitter group number score point mdash mdash ...
21924,Captains' War,gather resource build crew fight rival claim p...,gather resource build crew fight rival claim p...

In [16]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(data['ProcessedDescription'])

In [17]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1444589 stored elements and shape (21924, 127305)>

In [22]:
def get_similar_games(game_name, top_n = 5):
    idx = data[data['Name'] == game_name].index[0]

    cosine_sim = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()

    similar_indices = cosine_sim.argsort()[-top_n-1:-1][::-1]

    similar_games = data.iloc[similar_indices]['Name'].values

    return similar_games

In [23]:
game = 'Catan'
similar_games = get_similar_games(game)

similar_games

array(['The Settlers of Zarahemla', 'CATAN: 3D Edition',
       'The Settlers of Catan (containing 5/6 player expansion)',
       'Simply Catan', 'Baden-Württemberg Catan'], dtype=object)